# .streamlit/secrets.toml

# Clave de API de Google
google_api_key = "AIzaSyAOfajKbLocS4O2ZCfbr3KW57YjJWTarBs"

# Credenciales de la Base de Datos
[db_credentials]
user = "u241824557_than"
password = "1541100Luis"
host = "82.197.82.125"
database = "u241824557_lbusiness"

# <<< NUEVO >>> Credenciales del Servicio de Google Cloud (para Voz a Texto)
# Pega aquí el contenido COMPLETO de tu archivo JSON de credenciales.
[gcp_service_account]
type = "service_account"
project_id = "tu-proyecto-id"
private_key_id = "tu_private_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\nTu\nclave\nprivada\naquí\n-----END PRIVATE KEY-----\n"
client_email = "tu-email-de-servicio@tu-proyecto-id.iam.gserviceaccount.com"
client_id = "tu_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/..."
universe_domain = "googleapis.com"