# .streamlit/secrets.toml

# Clave de API de Google
google_api_key = "AIzaSyAOfajKbLocS4O2ZCfbr3KW57YjJWTarBs"

# Credenciales de la Base de Datos
[db_credentials]
user = "u241824557_than"
password = "1541100Luis"
host = "82.197.82.125"
database = "u241824557_lbusiness"